### PR TITLE
Update members.md

### PR DESCRIPTION
**Pull request by wendy-chan**
- [@wendy-chan](https://github.com/wendy-chan)

### CODE REVIEW

**Comment by ontouchstart** [comment]
@wendy-chan why did you close it?

**Comment by wendy-chan** [comment]
because it seems replay wrong~

**Comment by ontouchstart** [comment]
How?

**Comment by ontouchstart** [comment]
This looks ok to me https://github.com/wendy-chan/NtLtC/blob/035f18d63009ea18de410a9b77668fa6be3f08ad/members.md

Can you reopen this pull request?

**Pull request merged**
